# ~/.config/kitty/kitty.conf
# Evita que las aplicaciones sobrescriban la opacidad global de la terminal
dynamic_background_opacity yes
font_family      FiraCode Nerd Font
font_size        14.0
background_opacity 0.75
confirm_os_window_close 0
# Ajusta el valor en píxeles (ejemplo: 10 o 15)
window_padding_width 10 30 20 

remember_window_size  no
initial_window_width  100
initial_window_height 100


# Esto añade 1 píxel de espacio extra entre cada línea de texto
modify_font cell_height 20px

inactive_text_alpha 1.0
# Asegúrate de que no haya un 'inactive_background' definido con un color sólido

# BEGIN_KITTY_THEME
# Neowave
include current-theme.conf
# END_KITTY_THEME
