-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "dolphin"

local menu = "rofi -show drun"

local browser = "firefox"

local editor = "vim"

--################

--## AUTOSTART ###

--################







--exec-once = mpvpaper -o "--loop --no-audio --video-zoom=0.145" ALL ~/Downloads/starry-night-moewalls-com.mp4

--exec-once = bash -c 'dir="$HOME/Downloads/bg" mapfile -t wallpapers < <(find "$dir" -type f -iname "*.jpg" | sort) i=0 while true; do pkill -x swaybg 2>/dev/null [ ${#wallpapers[@]} -gt 0 ] && swaybg -i "${wallpapers[$i]}" -m fill & i=$(( (i + 1) % ${#wallpapers[@]} )) sleep 1800 done'




-- Ejecuta en el segundo workspace el navegador

-- windowrulev1 = workspace, 2, classi:^(firefox)$



--###########################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- Todas las ventanas flotantes por defecto

-- windowrule = match:class ^(app.zen_browser.zen)$, float on, size 900 1200, center on

hl.window_rule({
    name  = "float_on_80",
    match = {
        class.* = true,
    },
    float = true,
    size = { 900, 750 },
    center = true,
})

hl.window_rule({
    name  = "float_on_81",
    match = {
        class = "^(kitty)$",
    },
    float = true,
    size = { 500, 350 },
    center = true,
})

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 1,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "master",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.93,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more
    },
})
hl.curve("easeOutQuint", {
    type = "bezier",
    points = { { 0.23, 1 }, { 0.32, 1 } },
})
hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { { 0.65, 0.05 }, { 0.36, 1 } },
})
hl.curve("linear", {
    type = "bezier",
    points = { { 0, 0 }, { 1, 1 } },
})
hl.curve("almostLinear", {
    type = "bezier",
    points = { { 0.5, 0.5 }, { 0.75, 1.0 } },
})
hl.curve("quick", {
    type = "bezier",
    points = { { 0.15, 0 }, { 0.1, 1 } },
})
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        --new_status = master
    },
})

-- Configuración global de dimensiones flotantes por defecto

hl.config({
    floating = {
        -- Define el tamaño inicial por defecto para ventanas flotantes (Ancho x Alto)
        -- Ejemplo: 900x600
        --override_interactive_effects = false
    },
})
-- NOTE: Section 'floating' may be a plugin or custom section; verify the output

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#gestures

--gestures {

--   workspace_swipe = false

--}

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

hl.config({
    misc = {
        focus_on_activate = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "O", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pin())

--pseudo, # dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.window.cycle_next())

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.window.alter_zorder("top"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("flatpak run app.zen_browser.zen"))

hl.bind("SUPER + M", hl.dsp.exec_cmd("grim ~/Pictures/screenshot_$(date +%Y-%m-%d_%H-%M-%s).png"))

hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/Pictures/screenshot_$(date +%Y-%m-%d_%H-%M-%s).png"))

hl.bind("SUPER + equal", hl.dsp.window.resize({ x = 18%, y = 2%, relative = true }), { repeating = true })

hl.bind("SUPER + minus", hl.dsp.window.resize({ x = -5%, y = -5%, relative = true }), { repeating = true })

-- Redimensionar solo vertical

hl.bind("SUPER + up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })

-- Super + ↑  → más alto

hl.bind("SUPER + down", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })

-- Super + ↓  → más bajo

hl.bind("SUPER + G", hl.dsp.window.resize({ x = exact, y = 900, relative = true }))

hl.bind("SUPER + G", hl.dsp.window.center())

hl.bind("SUPER + N", hl.dsp.window.resize({ x = exact, y = 400, relative = true }))

hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("pkill -SIGINT wf-recorder || wf-recorder -f ~/Videos/grabacion_$(date +%Y-%m-%d_%H-%M-%s).mp4"))

-- Redimensionar solo horizontal

hl.bind("SUPER + left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })

-- Super + ←  → más estrecho

hl.bind("SUPER + SHIFT + bracketleft", hl.dispatch("moveactive", "-40 0"))
hl.bind("SUPER + SHIFT + bracketright", hl.dispatch("moveactive", "40 0"))
hl.bind("SUPER + SHIFT + semicolon", hl.dispatch("moveactive", "0 -40"))
hl.bind("SUPER + SHIFT + apostrophe", hl.dispatch("moveactive", "0 40"))

hl.bind("SUPER + right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })

-- Super + →  → más ancho

-- Subir volumen

hl.bind(mainMod .. " + " .. "K", hl.dsp.exec_cmd("amixer set Master 25%+"))

-- Bajar volumen

hl.bind(mainMod .. " + " .. "H", hl.dsp.exec_cmd("amixer set Master 25%-"))

-- Silenciar

hl.bind(mainMod .. " + " .. "U", hl.dsp.exec_cmd("amixer set Master toggle"))

-- Subir brillo

hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd("brightnessctl s 5%+"))

-- Bajar brillo 

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("brightnessctl s 2%-"))

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd("brightnessctl s 1%-"))

-- Move focus with mainMod + arrow keys

--bind = $mainMod, left, movefocus, l

--bind = $mainMod, right, movefocus, r

--bind = $mainMod, up, movefocus, u

--bind = $mainMod, down, movefocus, d

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- Example special workspace (scratchpad)

--bind = $mainMod, S, togglespecialworkspace, magic

--bind = $mainMod SHIFT, S, movetoworkspace, special:magic

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { repeating = true, locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Aumentar zoom (Super + Scroll arriba)

hl.bind("SUPER + mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/float/ {print $2 + 0.1}' )"))

-- Disminuir zoom (Super + Scroll abajo)

hl.bind("SUPER + mouse_down", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/float/ {print $2 - 0.1}' )"))

-- Resetear zoom a 1.0 (Super + 0)

hl.bind("SUPER + 0", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("brightnessctl s 200")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("waybar")
    hl.exec_cmd("app.zen_browser.zen")
    hl.exec_cmd("dunst")
    hl.exec_cmd("gammastep")
    hl.exec_cmd("swaybg -i Downloads/bg/starry-skies-and-cozy-nights-ge-1920x1200.jpg")
    hl.exec_cmd("sh -c 'UPPER_LIMIT=80; LOWER_LIMIT=20; while true; do LEVEL=$(cat /sys/class/power_supply/BAT0/capacity); STATUS=$(cat /sys/class/power_supply/BAT0/status); if [ \"$LEVEL\" -ge \"$UPPER_LIMIT\" ] && [ \"$STATUS\" = \"Charging\" ]; then dunstify -u critical -i battery-full-charged \"Batería al $LEVEL%\" \"Desconecta el cargador\"; elif [ \"$LEVEL\" -le \"$LOWER_LIMIT\" ] && [ \"$STATUS\" = \"Discharging\" ]; then dunstify -u critical -i battery-caution \"Batería Baja\" \"Nivel al $LEVEL%. Conecta el cargador\"; fi; sleep 120; done'")
    hl.exec_cmd("bash -c 'while true; do bat_lvl=$(cat /sys/class/power_supply/BAT0/capacity); bat_st=$(cat /sys/class/power_supply/BAT0/status); if [ \"$bat_lvl\" -le 10 ] && [ \"$bat_st\" = \"Discharging\" ]; then notify-send -u critical \"Batería Baja\" \"Se te olvidó conectar el cargador\"; elif [ \"$bat_lvl\" -ge 90 ] && [ \"$bat_st\" = \"Charging\" ]; then notify-send -u normal \"Batería Llena\" \"Se te olvidó desconectar el cargador\"; fi; sleep 60; done'")
    hl.exec_cmd("sleep $(( ( $(date -d \"20:00\" +%s) - $(date +%s)+ 86400 )% 86400 )) && dunstify \"Recordatorio\" \"Ya son las 8:00 PM\" -i clock")
    hl.exec_cmd("sleep $(( ( $(date -d \"20:30\" +%s) - $(date +%s)+ 86400 )% 86400 )) && dunstify \"Recordatorio\" \"Ya son las 8:30 PM\" -i clock")
end)
